CREATE TABLE post_table
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(128)                            NOT NULL,
    body  VARCHAR(4096)                           NOT NULL
);

CREATE TABLE person_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(64)                             NOT NULL,
    last_name  VARCHAR(64)                             NOT NULL
);