CREATE TABLE post_table
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(128)                            NOT NULL UNIQUE,
    body  VARCHAR(4096)                           NOT NULL
);